"""empty message

Revision ID: 1352488e3e
Revises: 26743c3ac34
Create Date: 2015-08-24 15:59:37.013623

"""

# revision identifiers, used by Alembic.
revision = '1352488e3e'
down_revision = '26743c3ac34'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pokemon_moves',
    sa.Column('pokemon_id', sa.Integer(), nullable=True),
    sa.Column('move_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['move_id'], ['moves.id'], ),
    sa.ForeignKeyConstraint(['pokemon_id'], ['pokemon.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pokemon_moves')
    ### end Alembic commands ###
