"""empty message

Revision ID: 1a78ca04317
Revises: 58f5c6e3102
Create Date: 2015-08-22 14:05:32.122744

"""

# revision identifiers, used by Alembic.
revision = '1a78ca04317'
down_revision = '58f5c6e3102'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('power', sa.Integer(), nullable=True),
    sa.Column('pp', sa.Integer(), nullable=True),
    sa.Column('accuracy', sa.Integer(), nullable=True),
    sa.Column('effect', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('natures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('bonus', sa.String(), nullable=True),
    sa.Column('penalty', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('natures')
    op.drop_table('moves')
    ### end Alembic commands ###
