"""empty message

Revision ID: 2195b0c4a81
Revises: 1352488e3e
Create Date: 2015-08-24 16:00:37.622119

"""

# revision identifiers, used by Alembic.
revision = '2195b0c4a81'
down_revision = '1352488e3e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
