"""empty message

Revision ID: 2391bd8f71d
Revises: a1d7dc0f2b
Create Date: 2015-08-29 17:12:25.382467

"""

# revision identifiers, used by Alembic.
revision = '2391bd8f71d'
down_revision = 'a1d7dc0f2b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
