"""empty message

Revision ID: 26743c3ac34
Revises: 1a78ca04317
Create Date: 2015-08-22 14:29:25.468511

"""

# revision identifiers, used by Alembic.
revision = '26743c3ac34'
down_revision = '1a78ca04317'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
