"""empty message

Revision ID: 2fcb59acffc
Revises: 223b8502c8e
Create Date: 2015-08-24 21:13:38.990138

"""

# revision identifiers, used by Alembic.
revision = '2fcb59acffc'
down_revision = '223b8502c8e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
