"""empty message

Revision ID: 4a66c6215b0
Revises: 2195b0c4a81
Create Date: 2015-08-24 16:02:58.782566

"""

# revision identifiers, used by Alembic.
revision = '4a66c6215b0'
down_revision = '2195b0c4a81'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
